services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    env_file:
      - ./backend/.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data1:/data/db

volumes:
  mongo_data1: